### PR TITLE
Remove zoneid memory check, it's a bit faster without it.

### PR DESCRIPTION
**Pull request by viti95**
Also disable Z_CheckHeap() as is only intended for debugging purposes

### CODE REVIEW

**Comment by goshhhy** [comment]
thanks!

i'd prefer an approach putting this functionality behind an #ifdef - say, the existing DEBUG flag

zoneid checking slows things down, but it's very useful if you're reworking a lot of memory management code, to help you figure out when things have gone very wrong - and i _might_ be doing that soon, pulling bits and pieces from my other quake fork uquake, as well as the nintendo ds ports

**Comment by viti95** [comment]
Well that's a better idea, having a DEBUG flag to disable zoneid check is much better. In my testings this change made my 5x86 about 8% faster. Maybe you can also check the PocketQuake port, it has implemented fixed point span drawing functions and those should be way faster on 486 processors.

**Comment by goshhhy** [comment]
interesting - i'll have to look into that. i'm not necessarily interested in having that be a default, but having it as an option would be good.

what i've been investigating for this project is whether it would be possible to implement a span renderer that works on a const-z basis, which i think could be done faster than the current algorithm with identical accuracy. however, i haven't been able to work on it much in the past month.

**Comment by viti95** [comment]
Oops, I was making some tests in my repo and those weren't mean to be included in this pull request, how can I remove them from this pull request?

**Comment by goshhhy** [comment]
it's no issue. i manually merged your initial commit, and left the other two out. i'll update the codebase later reintroducing the zoneid check, but behind an ifdef (unless someone else gets to it first). thanks!

**Pull request closed without merging**
